services:
  sociale:
    depends_on:
      - db
    image: ghcr.io/antonipokrzywa/sociale:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
volumes:
  pgdata:
  logs: